"""English descriptions and instructions for scripts/semantic_views.py (--lang en).

Only the prose the model reads changes. Synonyms, verified-query questions and
column aliases stay Finnish: they match what users type and what they see.
Keyed by the Finnish text; semantic_views.py fails if a string has no entry.
"""

EN = {
 "Liiga 2026-27 ennuste: lopullinen runkosarjataulukko, sarjavyöhykkeet, tulevien otteluiden voittotodennäköisyydet, joukkuevahvuudet ja pelaajaennusteet.": "Liiga 2026-27 forecast: final regular-season table, table zones, win probabilities for upcoming games, team strengths and player projections.",
 "Ennustettu LOPULLINEN runkosarjataulukko (60 ottelua) 10 000 simulaatiosta. Sisältää jo pelattujen otteluiden pisteet.": "Forecast FINAL regular-season table (60 games) from 10,000 simulations. Already includes points from games played.",
 "Joukkue": "Team",
 "Ennustettu loppusija, 1 = runkosarjan voittaja": "Forecast final rank, 1 = regular-season winner",
 "Ennustetut loppupisteet (keskiarvo)": "Forecast final points (mean)",
 "Pisteiden alaraja (5 %)": "Points, lower bound (5th percentile)",
 "Pisteiden yläraja (95 %)": "Points, upper bound (95th percentile)",
 "Todennäköisyys voittaa RUNKOSARJA (ei mestaruus -- pudotuspelejä malli ei ennusta)": "Probability of winning the REGULAR SEASON (not the championship: the model does not forecast playoffs)",
 "Yleisöennusteen pisteet": "Crowd-forecast points",
 "Yleisöennusteen sija": "Crowd-forecast rank",
 "Todennäköisyys päätyä kullekin sarjavyöhykkeelle.": "Probability of finishing in each table zone.",
 "1.-6. eli suoraan puolivälieriin": "Ranks 1-6: straight to the quarterfinals",
 "7.-10. eli säälipudotuspeleihin": "Ranks 7-10: play-in round",
 "1.-10. eli pudotuspeleihin millä tahansa reitillä": "Ranks 1-10: playoffs by either route",
 "15.-17. eli putoaa sarjasta": "Ranks 15-17: relegated",
 "Pelaamattomat ottelut ja uusimman ennusteen voittotodennäköisyydet. Voitto sisältää jatkoajan ja voittolaukaukset.": "Unplayed games with win probabilities from the latest forecast. A win includes overtime and shootout.",
 "Ottelun tunniste": "Game id",
 "Kotijoukkue": "Home team",
 "Vierasjoukkue": "Away team",
 "Alkamisaika Suomen aikaa (HH:MI)": "Start time, Finnish time (HH:MI)",
 "Todennäköisempi voittaja": "More likely winner",
 "Kotijoukkueen voittotodennäköisyys": "Home team win probability",
 "Vierasjoukkueen voittotodennäköisyys": "Away team win probability",
 "Todennäköisyys jatkoajalle": "Probability of overtime",
 "Suosikin voittotodennäköisyys": "Favourite's win probability",
 "Ottelupäivä Suomen aikaa": "Game date, Finnish time",
 "Ennusteen kehitys: yksi rivi per joukkue per päivittäinen ajo.": "Forecast history: one row per team per daily run.",
 "Ennustettu loppusija sinä päivänä": "Forecast final rank on that day",
 "Ennustetut loppupisteet sinä päivänä": "Forecast final points on that day",
 "Runkosarjan voiton todennäköisyys": "Regular-season win probability",
 "Pelattuja otteluita koko sarjassa sinä päivänä": "Games played league-wide on that day",
 "Ennusteen päivä": "Forecast date",
 "Mallin joukkuevahvuudet. OFF_RATING suurempi = parempi hyökkäys; DEF_RATING ja GOALIE_MULT pienempi = parempi.": "Model team strengths. OFF_RATING higher = better attack; DEF_RATING and GOALIE_MULT lower = better.",
 "Hyökkäysvoima": "Attack strength",
 "Puolustus (pienempi parempi)": "Defence (lower is better)",
 "Maalivahtikerroin (pienempi parempi)": "Goaltending multiplier (lower is better)",
 "Pelaajien ennusteista laskettu maalimäärä / ottelu": "Goals per game implied by the player projections",
 "Mallin pelaajakohtainen ennuste per ottelu, nykyinen rosteri.": "Model projection per game for each player on the current roster.",
 "Pelaaja": "Player",
 "F = hyökkääjä, D = puolustaja, G = maalivahti": "F = forward, D = defender, G = goalie",
 "Ennustetut maalit / ottelu": "Projected goals per game",
 "Ennustetut tehopisteet / ottelu": "Projected points per game",
 "Milloin ennuste päivitettiin ja montako ottelua oli pelattu (1 rivi).": "When the forecast was updated and how many games had been played (1 row).",
 "Päivityshetki (UTC)": "Update time (UTC)",
 "Pelattuja otteluita": "Games played",
 "Otteluita kaudella yhteensä": "Games in the season",
 "Joukkueiden nimet ovat tarkkoja merkkijonoja: HIFK, HPK, Ilves, JYP, Jokerit, Jukurit, K-Espoo, KalPa, KooKoo, Kärpät, Lukko, Pelicans, SaiPa, Sport, TPS, Tappara, Ässät.\nTodennäköisyydet ovat 0-1 -lukuja: näytä prosentteina (* 100), 1 desimaali.\n\"Tänään\" = TO_DATE(CONVERT_TIMEZONE('Europe/Helsinki', CURRENT_TIMESTAMP())) (Suomen aika, ei session aikavyöhyke).\nKausi 2027 = 2026-27. Pisteet: 3 varsinaisen peliajan voitto, 2 jatkoaika-\ntai voittolaukausvoitto, 1 jatkoaika- tai voittolaukaustappio, 0 tappio.\nSarjavyöhykkeet 2026-27: 1.-6. suoraan puolivälieriin, 7.-10. säälipudotuspeleihin,\n11.-14. ulkona, 15.-17. putoaa (uutta tällä kaudella).\nPalauta vain kysymykseen tarvittavat sarakkeet ja enintään 17 riviä.\nSTANDINGS on LOPULLINEN ennuste. Nykyinen sarjatilanne ei ole tässä mallissa.\nTulevat ottelut: käytä aina UPCOMING_GAMES, se on jo uusin ennuste.": "Team names are exact strings: HIFK, HPK, Ilves, JYP, Jokerit, Jukurit, K-Espoo, KalPa, KooKoo, Kärpät, Lukko, Pelicans, SaiPa, Sport, TPS, Tappara, Ässät.\nProbabilities are 0-1 fractions: show as percentages (* 100), 1 decimal.\n\"Today\" = TO_DATE(CONVERT_TIMEZONE('Europe/Helsinki', CURRENT_TIMESTAMP())) (Finnish time, not the session time zone).\nSeason 2027 = 2026-27. Points: 3 regulation win, 2 overtime/shootout win,\n1 overtime/shootout loss, 0 regulation loss.\nTable zones 2026-27: 1-6 straight to quarterfinals, 7-10 play-in round,\n11-14 out, 15-17 relegated (new this season).\nReturn only the columns the question needs, at most 17 rows.\nSTANDINGS is the FINAL forecast. The current table is not in this model.\nUpcoming games: always use UPCOMING_GAMES, it already holds the latest forecast.",
 "Vain Liiga 2026-27 runkosarja. Ei pudotuspelejä\neikä muita sarjoja. Kysymys nykyisestä sarjatilanteesta, pelatuista otteluista,\npistepörssistä tai mallin osuvuudesta kuuluu toiselle työkalulle.": "Liiga 2026-27 regular season only. No playoffs, no other leagues.\nQuestions about the current table, played games, scoring leaders or model\naccuracy belong to the other tool.",
 "Liiga 2026-27 toteuma: sarjatilanne nyt, tulokset, mallin osuvuus, yllättäjät, pistepörssi, maalivahdit, kokoonpanot ja aiemmat kaudet.": "Liiga 2026-27 so far: current table, results, model accuracy, surprises, scoring leaders, goalies, lineups and past seasons.",
 "Toteutunut sarjatilanne NYT ja joukkueen kausi tähän asti. TABLE_RANK on liiga.fi:n järjestys (pisteet, maaliero, tehdyt).": "Actual table NOW and each team's season so far. TABLE_RANK is the liiga.fi order (points, goal difference, goals for).",
 "Sija sarjataulukossa nyt": "Rank in the table now",
 "Pelatut ottelut": "Games played",
 "Pisteet": "Points",
 "Voitot varsinaisella peliajalla": "Regulation wins",
 "Jatkoaika- ja voittolaukausvoitot": "Overtime and shootout wins",
 "Jatkoaika- ja voittolaukaustappiot": "Overtime and shootout losses",
 "Tappiot varsinaisella peliajalla": "Regulation losses",
 "Tehdyt maalit": "Goals for",
 "Päästetyt maalit": "Goals against",
 "Maaliero": "Goal difference",
 "Pisteet viidestä viimeisestä ottelusta": "Points from the last five games",
 "Pisteet kotiotteluista": "Points from home games",
 "Pisteet vierasotteluista": "Points from away games",
 "Maaliodottama, tehdyt (xG)": "Expected goals for (xG)",
 "Maaliodottama, päästetyt (xGA)": "Expected goals against (xGA)",
 "Varjosarjataulukon pisteet: mitä maalipaikat (xG) olisivat antaneet": "Shadow-table points: what the chances (xG) would have earned",
 "Pisteet miinus varjopisteet: + = onnekas": "Points minus shadow points: + = lucky",
 "Esikauden ennusteen pisteet juuri pelatuista otteluista": "Points the pre-season forecast expected from exactly these games",
 "Pisteet miinus esikauden odotus: + = yllättänyt positiivisesti": "Points minus pre-season expectation: + = positive surprise",
 "Ylivoimaprosentti (0-1)": "Power-play percentage (0-1)",
 "Alivoiman onnistuminen (0-1)": "Penalty-kill success (0-1)",
 "Kuluvan kauden kaikki ottelut: tulokset ja otteluohjelma.": "All games of the current season: results and schedule.",
 "TRUE = pelattu": "TRUE = played",
 "regulation / overtime / shootout": "regulation / overtime / shootout",
 "Voittaja": "Winner",
 "Alkamisaika Suomen aikaa": "Start time, Finnish time",
 "Kotijoukkueen maalit": "Home team goals",
 "Vierasjoukkueen maalit": "Away team goals",
 "Kotijoukkueen xG": "Home team xG",
 "Vierasjoukkueen xG": "Away team xG",
 "Yleisömäärä": "Attendance",
 "Jokainen pelattu ottelu verrattuna mallin viimeisimpään ennusteeseen ennen ottelua. Vertailutaso on 'kotijoukkue voittaa aina', ei 50 %.": "Every played game against the model's last forecast before the game. The baseline is 'home team always wins', not 50 %.",
 "Toteutunut voittaja": "Actual winner",
 "Mallin suosikki": "Model favourite",
 "1 = malli ennusti voittajan oikein": "1 = model picked the winner",
 "1 = kotijoukkue voitti (vertailutaso)": "1 = home team won (baseline)",
 "Mallin antama kotivoiton todennäköisyys": "Model's home win probability",
 "Todennäköisyys jonka malli antoi voittajalle: pieni = yllätystulos": "Probability the model gave the eventual winner: low = upset",
 "Suosikin todennäköisyys": "Favourite's probability",
 "Log-loss, pienempi parempi": "Log-loss, lower is better",
 "Brier-pisteet, pienempi parempi": "Brier score, lower is better",
 "Ottelupäivä": "Game date",
 "Osumaprosentti (0-1)": "Hit rate (0-1)",
 "Kotijoukkueen voittoprosentti (vertailutaso, 0-1)": "Home team win rate (baseline, 0-1)",
 "Kenttäpelaajien kausi nyt (pistepörssi). Maalit ilman epäonnistuneita rangaistuslaukauksia. Ottelut kokoonpanoista.": "Skaters' season so far (scoring leaders). Goals exclude missed penalty shots. Games from lineups.",
 "Hyökkääjä / Puolustaja": "Values: 'Hyökkääjä' (forward) or 'Puolustaja' (defender)",
 "Maalit": "Goals",
 "Syötöt": "Assists",
 "Tehopisteet": "Points",
 "Tehopisteet / ottelu": "Points per game",
 "Ylivoimamaalit": "Power-play goals",
 "Voittomaalit": "Game-winning goals",
 "Esikauden ennuste × pelatut ottelut": "Pre-season projection × games played",
 "Pisteet yli (+) tai ali (−) esikauden ennusteen": "Points above (+) or below (−) the pre-season projection",
 "Maalivahtien kausi nyt. Torjunta-%:a ei ole (liiga.fi ei julkaise laukauksia); vertailu tehdään päästetyillä vs. odotus samoista maalipaikoista. Vertailut vain otteluista joissa pelasi yksi maalivahti.": "Goalies' season so far. No save percentage (liiga.fi publishes no shots); goals against are compared with what was expected from the same chances. Only games one goalie played alone.",
 "Maalivahti": "Goalie",
 "Aloitukset": "Starts",
 "Ottelut koko ottelun yksin": "Games played start to finish",
 "Päästetyt maalit (yksin pelatut)": "Goals against (solo games)",
 "Päästetyt / ottelu": "Goals against per game",
 "Maaleja vähemmän (+) kuin keskivertomaalivahti samoista paikoista": "Goals fewer (+) than an average goalie would have allowed from the same chances",
 "Maaleja vähemmän (+) kuin oma esikauden ennuste": "Goals fewer (+) than the goalie's own pre-season projection",
 "Joukkueen viimeisimmän pelatun ottelun kokoonpano = todennäköisin seuraava.": "Lineup from the team's most recent played game = most likely next lineup.",
 "Vastustaja siinä ottelussa": "Opponent in that game",
 "Pelipaikka": "Position, in Finnish (e.g. 'Keskushyökkääjä', 'Maalivahti')",
 "F / D / G": "F / D / G",
 "Kapteeni": "Captain",
 "Maalivahti aloitti": "Goalie started",
 "Ketju / pari (1-4)": "Line or pair (1-4)",
 "Pelinumero": "Jersey number",
 "Ottelun päivä": "Game date",
 "Joukkueiden kaudet 2022-2027 (2026 = kausi 2025-26).": "Team seasons 2022-2027 (2026 = season 2025-26).",
 "Kausi, 2026 = 2025-26": "Season, 2026 = 2025-26",
 "Ottelut": "Games",
 "Voitot": "Wins",
 "Tehdyt": "Goals for",
 "Päästetyt": "Goals against",
 "xG-osuus": "xG share",
 "Joukkueiden nimet ovat tarkkoja merkkijonoja: HIFK, HPK, Ilves, JYP, Jokerit, Jukurit, K-Espoo, KalPa, KooKoo, Kärpät, Lukko, Pelicans, SaiPa, Sport, TPS, Tappara, Ässät.\nTodennäköisyydet ovat 0-1 -lukuja: näytä prosentteina (* 100), 1 desimaali.\n\"Tänään\" = TO_DATE(CONVERT_TIMEZONE('Europe/Helsinki', CURRENT_TIMESTAMP())) (Suomen aika, ei session aikavyöhyke).\nKausi 2027 = 2026-27. Pisteet: 3 varsinaisen peliajan voitto, 2 jatkoaika-\ntai voittolaukausvoitto, 1 jatkoaika- tai voittolaukaustappio, 0 tappio.\nSarjavyöhykkeet 2026-27: 1.-6. suoraan puolivälieriin, 7.-10. säälipudotuspeleihin,\n11.-14. ulkona, 15.-17. putoaa (uutta tällä kaudella).\nPalauta vain kysymykseen tarvittavat sarakkeet ja enintään 17 riviä.\nMallin osuvuus: vertaa aina HIT_RATEa kotijoukkueen voittoprosenttiin, ei 50 %:iin.\nYllättäjä = POINTS_VS_PRESEASON (joukkue, pelaaja) tai GOALS_SAVED_VS_PRESEASON (maalivahti).\nPelaajalistoissa vaadi GAMES_PLAYED >= 5 ellei toisin kysytä.": "Team names are exact strings: HIFK, HPK, Ilves, JYP, Jokerit, Jukurit, K-Espoo, KalPa, KooKoo, Kärpät, Lukko, Pelicans, SaiPa, Sport, TPS, Tappara, Ässät.\nProbabilities are 0-1 fractions: show as percentages (* 100), 1 decimal.\n\"Today\" = TO_DATE(CONVERT_TIMEZONE('Europe/Helsinki', CURRENT_TIMESTAMP())) (Finnish time, not the session time zone).\nSeason 2027 = 2026-27. Points: 3 regulation win, 2 overtime/shootout win,\n1 overtime/shootout loss, 0 regulation loss.\nTable zones 2026-27: 1-6 straight to quarterfinals, 7-10 play-in round,\n11-14 out, 15-17 relegated (new this season).\nReturn only the columns the question needs, at most 17 rows.\nModel accuracy: always compare HIT_RATE with the home team win rate, not 50 %.\nSurprise = POINTS_VS_PRESEASON (team, player) or GOALS_SAVED_VS_PRESEASON (goalie).\nPlayer lists: require GAMES_PLAYED >= 5 unless asked otherwise.",
 "Vain Liiga. Ennusteet lopputaulukosta tai\ntulevista otteluista kuuluvat toiselle työkalulle.": "Liiga only. Forecasts of the final table or upcoming games belong\nto the other tool.",
 "Kierroksen esikatselu: tuleva ottelu, ennuste, molempien joukkueiden sija, pisteet ja vire, todennäköinen maalivahti ja keskinäiset ottelut tällä kaudella. Yksi rivi per ottelu.": "Round preview: upcoming game, forecast, both teams' rank, points and form, likely goalie and this season's head-to-head. One row per game.",
 "Kotijoukkueen todennäköinen maalivahti (aloitti edellisen ottelun)": "Home team's likely goalie (started the previous game)",
 "Vierasjoukkueen todennäköinen maalivahti (aloitti edellisen ottelun)": "Away team's likely goalie (started the previous game)",
 "Kotijoukkueen sija nyt": "Home team's current rank",
 "Vierasjoukkueen sija nyt": "Away team's current rank",
 "Kotijoukkueen pisteet nyt": "Home team's current points",
 "Vierasjoukkueen pisteet nyt": "Away team's current points",
 "Kotijoukkueen pisteet 5 viime ottelusta": "Home team's points from the last 5 games",
 "Vierasjoukkueen pisteet 5 viime ottelusta": "Away team's points from the last 5 games",
 "Kotimaalivahdin maalit vähemmän (+) kuin keskiverto": "Home goalie: goals fewer (+) than an average goalie",
 "Vierasmaalivahdin maalit vähemmän (+) kuin keskiverto": "Away goalie: goals fewer (+) than an average goalie",
 "Keskinäiset ottelut tällä kaudella": "Head-to-head games this season",
 "Kotijoukkueen voitot keskinäisissä": "Home team's head-to-head wins",
 "Vierasjoukkueen voitot keskinäisissä": "Away team's head-to-head wins",
 "Kierroksen esikatselu valmiina suomenkielisinä riveinä: yksi rivi per tuleva ottelu. Kopioi tekstisarakkeet sellaisenaan.": "Round preview as ready Finnish lines: one row per upcoming game. Copy the text columns verbatim.",
 "Otsikkorivi: aika, koti – vieras": "Heading line: time, home – away",
 "Ennusterivi: voittotodennäköisyydet ja jatkoaika": "Forecast line: win probabilities and overtime",
 "Tilannerivi: sija, pisteet ja vire (pisteet 5 viime ottelusta /15)": "Standing line: rank, points and form (points from the last 5 games, out of 15)",
 "Todennäköiset maalivahdit ja heidän maalinsa vähemmän (+) kuin keskiverto": "Likely goalies and their goals fewer (+) than an average goalie",
 "Keskinäiset ottelut tällä kaudella, tyhjä jos ei kohdattu": "Head-to-head this season, empty if the teams have not met",
 "Suosikkijoukkue, tai 'tasainen' jos alle 55 %": "Favourite, or 'tasainen' (even) below 55 %",
 "Suosikin voittotodennäköisyys prosentteina": "Favourite's win probability in percent",
 "Kotijoukkueen vire miinus vierasjoukkueen vire": "Home form minus away form",
 "Ennustettujen loppupisteiden keskiarvo": "Mean of the forecast final points",
 "Putoavien joukkueiden odotettu määrä (summa on aina 3)": "Expected number of relegated teams (always sums to 3)",
 "Tulevien otteluiden määrä": "Number of upcoming games",
 "Kotivoiton keskimääräinen todennäköisyys": "Mean home win probability",
 "Ylivoimatilanteet": "Power-play opportunities",
 "Alivoimalla päästetyt maalit": "Goals allowed while short-handed",
 "Alivoimatilanteet": "Short-handed situations",
 "Ylivoimaprosentti summista (0-1). Käytä tätä, älä PP_PCT:n keskiarvoa.": "Power-play percentage from totals (0-1). Use this, never the average of PP_PCT.",
 "Alivoiman onnistuminen summista (0-1)": "Penalty-kill success from totals (0-1)",
 "Tehdyt maalit per joukkueottelu": "Goals for per team game",
 "Pisteet per joukkueottelu": "Points per team game",
 "Pelattujen otteluiden määrä": "Number of games played",
 "Keskimääräinen yleisömäärä pelatuissa": "Average attendance in played games",
 "Maaleja per ottelu yhteensä (molemmat)": "Total goals per game (both teams)",
 "Kotivoittojen osuus pelatuista (0-1)": "Share of played games won by the home team (0-1)",
 "Log-lossin keskiarvo, pienempi parempi": "Mean log-loss, lower is better",
 "Brier-pisteiden keskiarvo, pienempi parempi": "Mean Brier score, lower is better",
 "Arvioitujen otteluiden määrä": "Number of games evaluated",
 "Maalit yhteensä": "Total goals",
 "Tehopisteet yhteensä": "Total points",
 "Maaleja vähemmän kuin keskiverto yhteensä": "Total goals fewer than an average goalie"
}
